---
matrix:
  DOCKER_VERSION:
  - 1.10.3
  - 1.11.2
  - 1.12.1
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.10.3
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_VERSION: ${DOCKER_VERSION}
    commands:
    - dapper ci
