---
matrix:
  DOCKER_VERSION:
  - 1.12.1
  - 1.13.1
  - 17.03.0-ce
  - 17.06.0-ce
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.11.2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_VERSION: ${DOCKER_VERSION}
    commands:
    - dapper ci
