FROM golang:1.7.5
RUN apt-get update && \
    apt-get install -y uuid-runtime iptables
RUN go get github.com/rancher/trash
RUN go get github.com/golang/lint/golint
ARG DOCKER_VERSION=1.10.3
RUN if [ "${DOCKER_VERSION}" = "1.10.3" ]; then \
        curl -sL https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION} > /usr/bin/docker && \
        chmod +x /usr/bin/docker; \
    fi
RUN if [ "${DOCKER_VERSION}" != "1.10.3" ]; then \
        curl -sfL https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz | tar xzf - -C /usr/bin --strip-components=1; \
    fi
ENV PATH /go/bin:$PATH
ENV DAPPER_SOURCE /go/src/github.com/rancher/agent
ENV DAPPER_OUTPUT bin dist
ENV DAPPER_ENV TAG REPO CROSS
ENV DAPPER_RUN_ARGS --privileged
ENV GO15VENDOREXPERIMENT 1
ENV TRASH_CACHE ${DAPPER_SOURCE}/.trash-cache
WORKDIR ${DAPPER_SOURCE}

RUN apt-get update && \
    apt-get install -y \
        python-tox

VOLUME "/var/lib/docker"
ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
