#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

OS_PLATFORM_ARG=(linux windows)
OS_ARCH_ARG[linux]="amd64"
OS_ARCH_ARG[windows]="amd64"

mkdir -p bin
CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION -linkmode external -extldflags -static -s" -o bin/agent
