#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/agent .
docker build -t ${REPO}/agent:${TAG} .

echo Built ${REPO}/agent:${TAG}
