#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

if [ ! -e bin/agent ]; then
    ./scripts/build
fi

cd package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

cp ../bin/agent .

IMAGE=${REPO}/agent:${TAG}
docker build --build-arg IMAGE=${IMAGE} -t ${IMAGE} .
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
