#!/bin/bash
set -e

cleanup()
{
    local exit=$?
    kill $PID || true
    wait $PID || true
    umount /run/docker/netns/default || true
    umount /run || true
    exit $exit
}

cd $(dirname $0)/..

if grep -q overlay /proc/filesystems; then
    export STORAGE=overlay
else
    export STORAGE=aufs
fi
mount -t tmpfs none /run
docker daemon -s $STORAGE -D >/var/log/docker.log 2>&1 &
PID=$!
trap cleanup EXIT

sleep 1

docker info

ip link set dev eth0 mtu 1300
ip link set dev docker0 mtu 1300

IDS=$(docker ps -qa)
if [ -n "$IDS" ]; then
    docker kill $(docker ps -qa) || true
    docker rm -fv || true
fi

echo Running tests

docker pull ibuildthecloud/helloworld:latest

docker run -i -d busybox:1

PACKAGES=". $(find -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|.trash-cache|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"

go test -race -cover -timeout=5m -tags=test ${PACKAGES}
